"""restore_sso_tenancy_quota_v3

Revision ID: 4e1aa48ff9b2
Revises: d20d26ceefe6
Create Date: 2026-02-01 18:09:04.224158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e1aa48ff9b2'
down_revision: Union[str, Sequence[str], None] = 'd20d26ceefe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_password_hash', table_name='users')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_password_hash', 'users', ['password_hash'], unique=False)
    # ### end Alembic commands ###
