"""add sso config to system_settings

Revision ID: accf49c25da3
Revises: 1f50915e062a
Create Date: 2026-02-01 18:29:01.280052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accf49c25da3'
down_revision: Union[str, Sequence[str], None] = '1f50915e062a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('google_client_id', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('google_client_secret', sa.String(), nullable=True))
    op.add_column('system_settings', sa.Column('google_redirect_uri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'google_redirect_uri')
    op.drop_column('system_settings', 'google_client_secret')
    op.drop_column('system_settings', 'google_client_id')
    # ### end Alembic commands ###
